const wrapped = require('../util/wrap-children')
const all = require('../all')

const base = require('./base')
const blockquote = require('./blockquote')
const br = require('./break')
const code = require('./code')
const del = require('./strike-through')
const emphasis = require('./emphasis')
const heading = require('./heading')
const inlineCode = require('./inline-code')
const link = require('./link')
const paragraph = require('./paragraph')
const strong = require('./strong')
const wbr = require('./wbr')
const dl = undefined // require('./dl')
const listItem = require('./list-item')

exports.comment = ignore

// Ignore these elements because... They don't have a good mapping
exports.doctype = ignore
exports.applet = ignore
exports.area = ignore
exports.basefont = ignore
exports.bgsound = ignore
exports.caption = ignore
exports.col = ignore
exports.colgroup = ignore
exports.command = ignore
exports.content = ignore
exports.datalist = ignore
exports.dialog = ignore
exports.element = ignore
exports.embed = ignore
exports.frame = ignore
exports.frameset = ignore
exports.isindex = ignore
exports.keygen = ignore
exports.link = ignore
exports.math = ignore
exports.menu = ignore
exports.menuitem = ignore
exports.meta = ignore
exports.nextid = ignore
exports.noembed = ignore
exports.noframes = ignore
exports.optgroup = ignore
exports.option = ignore
exports.param = ignore
exports.script = ignore
exports.shadow = ignore
exports.source = ignore
exports.spacer = ignore
exports.style = ignore
exports.svg = ignore
exports.template = ignore
exports.title = ignore
exports.track = ignore

// Grab all children of these elements, forfeiting semantic meaning :(
exports.abbr = all
exports.acronym = all
exports.bdi = all
exports.bdo = all
exports.big = all
exports.blink = all
exports.button = all
exports.canvas = all
exports.cite = all
exports.data = all
exports.details = all
exports.dfn = all
exports.font = all
exports.ins = all
exports.label = all
exports.map = all
exports.marquee = all
exports.meter = all
exports.nobr = all
exports.noscript = all
exports.object = all
exports.output = all
exports.progress = all
exports.rb = all
exports.rbc = all
exports.rp = all
exports.rt = all
exports.rtc = all
exports.ruby = all
exports.slot = all
exports.small = all
exports.span = all
exports.sup = all
exports.sub = all
exports.tbody = all
exports.tfoot = all
exports.thead = all
exports.time = all

// Wrap in... what exactly?
exports.address = wrapped
exports.article = wrapped
exports.aside = wrapped
exports.body = wrapped
exports.center = wrapped
exports.div = wrapped
exports.fieldset = wrapped
exports.figcaption = wrapped
exports.figure = wrapped
exports.form = wrapped
exports.footer = wrapped
exports.header = wrapped
exports.hgroup = wrapped
exports.html = wrapped
exports.legend = wrapped
exports.main = wrapped
exports.multicol = wrapped
exports.nav = wrapped
exports.picture = wrapped
exports.section = wrapped

// Specific handlers
exports.a = link
exports.audio = ignore
exports.b = strong
exports.base = base
exports.blockquote = blockquote
exports.br = br
exports.code = inlineCode
exports.dir = ignore
exports.dl = dl
exports.dt = listItem
exports.dd = listItem
exports.del = del
exports.em = emphasis
exports.h1 = heading
exports.h2 = heading
exports.h3 = heading
exports.h4 = heading
exports.h5 = heading
exports.h6 = heading
exports.hr = ignore
exports.i = emphasis
exports.iframe = ignore
exports.img = ignore
exports.image = ignore
exports.input = ignore
exports.kbd = inlineCode
exports.li = listItem
exports.listing = code
exports.mark = emphasis
exports.ol = wrapped
exports.p = paragraph
exports.plaintext = code
exports.pre = code
exports.q = ignore
exports.s = del
exports.samp = inlineCode
exports.select = ignore
exports.strike = del
exports.strong = strong
exports.summary = paragraph
exports.table = ignore
exports.td = ignore
exports.textarea = ignore
exports.th = ignore
exports.tr = ignore
exports.tt = inlineCode
exports.u = emphasis
exports.ul = wrapped
exports.const = inlineCode
exports.video = ignore
exports.wbr = wbr
exports.xmp = code

function ignore() {
  /* intentional noop */
}
